services:
  postgres_db:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 2s
      timeout: 30s
      retries: 5
    ports:
      - 5433:5432
  
  api:
    build:
      dockerfile: Dockerfile
    env_file: '.env'
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - 8005:8000
    develop:
      watch:
        - action: sync
          path: .
          target: .
